const dataImbarazzo = [
    "Non ho mai salutato con entusiasmo qualcuno da lontano, per poi scoprire che non era chi pensavo.",
    "Non ho mai ricambiato un saluto con la mano, per poi accorgermi che la persona stava salutando qualcuno dietro di me.",
    "Non ho mai fatto finta di guardare intensamente il telefono per evitare di salutare un conoscente per strada.",
    "Non ho mai sbattuto violentemente contro un palo o un cartello stradale perché camminavo guardando il cellulare.",
    "Non ho mai lottato contro una porta tirandola con tutta la mia forza, per poi leggere il cartello 'SPINGERE'.",
    "Non ho mai sbattuto la faccia contro una porta a vetri talmente pulita da sembrare aperta.",
    "Non ho mai finto di zoppicare o guardare le scarpe per giustificare un inciampo plateale per strada.",
    "Non ho mai fatto una caduta epica in pubblico, rialzandomi in un millisecondo dicendo 'tutto a posto!'.",
    "Non ho mai scoppiato a ridere da solo in un luogo silenziosissimo guardando lo schermo del telefono.",
    "Non ho mai avuto un attacco di risa irrefrenabile in un momento totalmente inopportuno (es. funerale, cerimonia, sfuriata di qualcuno).",
    "Non ho mai parlato da solo ad alta voce o cantato, per poi accorgermi che qualcuno mi stava ascoltando.",
    "Non ho mai risposto 'Sì, ahah' a qualcuno che mi parlava perché non avevo capito niente, scoprendo poi che mi aveva fatto una domanda seria.",
    "Non ho mai chiamato 'mamma' o 'papà' un professore a scuola o il mio capo al lavoro.",
    "Non ho mai chiesto informazioni in un negozio a un perfetto sconosciuto, convinto/a che ci lavorasse.",
    "Non ho mai detto qualcosa di molto imbarazzante o cattivo su qualcuno che si trovava esattamente dietro di me.",
    "Non ho mai inviato uno screenshot di una conversazione... alla persona stessa con cui stavo conversando.",
    "Non ho mai mandato un messaggio compromettente o un insulto nel gruppo WhatsApp sbagliato.",
    "Non ho mai camminato in pubblico con un pezzo di carta igienica attaccato sotto la suola della scarpa.",
    "Non ho mai girato per ore con la patta dei pantaloni completamente abbassata senza che nessuno mi dicesse nulla.",
    "Non ho mai indossato una maglietta o un maglione al contrario per mezza giornata senza accorgermene.",
    "Non ho mai parlato a lungo a distanza ravvicinata con qualcuno avendo un pezzo di cibo incastrato tra i denti frontali.",
    "Non ho mai fatto un sorriso smagliante a qualcuno avendo il rossetto sbavato sui denti.",
    "Non ho mai sputato in faccia a qualcuno per sbaglio mentre parlavo con troppa foga.",
    "Non ho mai emesso un rumore 'sospetto' e imbarazzante con la sedia in un'aula silenziosa, cercando poi di riprodurlo per dimostrare che non era quello che pensavano.",
    "Non ho mai mollato una scorreggia 'silenziosa' in pubblico, pregando che nessuno sentisse l'odore.",
    "Non ho mai sbagliato clamorosamente il bagno in un locale, entrando in quello del sesso opposto.",
    "Non ho mai scoperto che mancava la carta igienica nei bagni di un locale pubblico solo DOPO aver finito.",
    "Non ho mai aperto con sicurezza la portiera di un'auto uguale alla mia, trovandoci dentro degli sconosciuti.",
    "Non ho mai inviato per sbaglio un vocale in cui sospiravo, canticchiavo o facevo versi strani.",
    "Non ho mai fatto finta di sapere di cosa si stesse parlando per ore, annuendo come un idiota.",
    "Non ho mai perso completamente il filo del discorso a metà di una frase importante, facendo scena muta.",
    "Non ho mai dimenticato il nome di una persona che mi si era appena presentata due secondi prima.",
    "Non ho mai dovuto presentare due persone tra loro essendomi scordato il nome di almeno una delle due.",
    "Non ho mai fatto una battuta in un gruppo di persone venendo accolto dal silenzio e dal gelo più totale.",
    "Non ho mai risposto al telefono dicendo 'Pronto?!' con voce squillante, per poi accorgermi che era partita una chiamata per sbaglio dalla mia tasca.",
    "Non ho mai lasciato squillare a volume altissimo un video imbarazzante in un luogo pubblico affollato (treno, sala d'attesa).",
    "Non ho mai arrossito in modo evidente e incontrollabile per un complimento ricevuto.",
    "Non ho mai arrossito per una semplice battuta a doppio senso, confermando praticamente di aver capito benissimo.",
    "Non ho mai fatto ciao con la mano a un manichino o a un riflesso in vetrina scambiandolo per una persona vera.",
    "Non ho mai finto di cercare disperatamente qualcosa nella borsa per evitare il contatto visivo con qualcuno.",
    "Non ho mai rovesciato platealmente il caffè o un drink sui miei vestiti (o peggio, su quelli di qualcun altro) al bar.",
    "Non ho mai fatto cadere un vassoio pieno in mensa o al fast food, attirando l'attenzione di tutto il locale.",
    "Non ho mai fatto cadere tutte le monete dal portafoglio alla cassa del supermercato, creando una fila chilometrica.",
    "Non ho mai confuso una donna leggermente in sovrappeso per una donna incinta, facendole le congratulazioni.",
    "Non ho mai sbagliato clamorosamente l'orario o il giorno di un appuntamento importante, presentandomi a vuoto.",
    "Non ho mai inviato un'email formale scrivendo 'in allegato' e dimenticandomi di inserire l'allegato.",
    "Non ho mai risposto con 'Grazie, altrettanto!' al cameriere che mi augurava 'Buon appetito'.",
    "Non ho mai salutato un estraneo che mi aveva detto 'Ciao', scoprendo che era al telefono con le cuffiette invisibili.",
    "Non ho mai finto di stare al telefono parlottando da solo per evitare di essere fermato per strada da qualcuno.",
    "Non ho mai aperto la fotocamera frontale del telefono dal basso, spaventandomi del mio stesso doppio mento.",
    "Non ho mai cercato disperatamente il mio cellulare mentre lo avevo letteralmente in mano o all'orecchio.",
    "Non ho mai cercato gli occhiali per tutta la casa mentre li avevo comodamente appoggiati sulla testa.",
    "Non ho mai usato un termine straniero o 'colto' in un discorso, sbagliandone totalmente il significato.",
    "Non ho mai pronunciato male in pubblico una parola comunissima, creando un doppio senso involontario.",
    "Non ho mai fatto finta di conoscere una band o un artista famoso solo per non sembrare ignorante.",
    "Non ho mai riavvolto mentalmente una scena imbarazzante successa 5 anni fa prima di addormentarmi.",
    "Non ho mai provato la carta di credito alla cassa, pregando divinità sconosciute che il PIN fosse giusto e la transazione passasse.",
    "Non ho mai sorriso a un cassiere o a un cameriere con la faccia colpevole per aver rotto qualcosa.",
    "Non ho mai detto a gran voce 'a me non succede mai!' ed esser smentito dal karma tre secondi dopo.",
    "Non ho mai fatto una figuraccia talmente grande da voler letteralmente sprofondare al centro della Terra."
];