const dataHot = [
    "Non ho mai baciato qualcuno al primo appuntamento.",
    "Non ho mai baciato qualcuno senza sapere nemmeno il suo cognome.",
    "Non ho mai baciato qualcuno in mezzo alla strada o sotto la pioggia.",
    "Non ho mai baciato qualcuno in un bagno di un locale.",
    "Non ho mai baciato due persone diverse nella stessa sera.",
    "Non ho mai limonato in macchina o sui divanetti di una discoteca.",
    "Non ho mai limonato con qualcuno sapendo che non l’avrei mai più rivisto.",
    "Non ho mai rubato un bacio all'improvviso per fare la prima mossa.",
    "Non ho mai provocato qualcuno fermandomi a un millimetro dalle sue labbra.",
    "Non ho mai fatto durare un abbraccio così a lungo da trasformarlo in un bacio.",
    "Non ho mai stretto a me qualcuno ballando, molto più del necessario.",
    "Non ho mai accarezzato i capelli di qualcuno con doppie intenzioni.",
    "Non ho mai fissato le labbra di qualcuno desiderando palesemente di baciarlo.",
    "Non ho mai sussurrato parole provocanti all’orecchio di qualcuno.",
    "Non ho mai fatto un complimento dal doppio senso malizioso sul corpo di qualcuno.",
    "Non ho mai flirtato con qualcuno che sapevo di non poter avere.",
    "Non ho mai lanciato uno sguardo che diceva molto più di mille parole.",
    "Non ho mai usato la scusa del freddo per avvicinarmi fisicamente.",
    "Non ho mai ricevuto o dato un bacio sul collo che mi ha tolto il respiro.",
    "Non ho mai morso il labbro di qualcuno intenzionalmente per stuzzicarlo.",
    "Non ho mai lasciato apposta un segno di rossetto sul collo o sulla camicia di qualcuno.",
    "Non ho mai mandato un messaggio con un doppio senso inequivocabile.",
    "Non ho mai scritto “sei sveglio?” dopo mezzanotte sperando in un certo epilogo.",
    "Non ho mai inviato un vocale usando un tono volutamente sensuale.",
    "Non ho mai cancellato un messaggio 'spinto' per vergogna subito dopo averlo inviato.",
    "Non ho mai riletto una chat piccante solo per riviverne l’atmosfera.",
    "Non ho mai fatto sexting (messaggi erotici).",
    "Non ho mai mandato una foto allo specchio o in accappatoio con il chiaro intento di sedurre.",
    "Non ho mai mandato una foto dal letto con secondi fini.",
    "Non ho mai ricevuto una foto hot che mi ha fatto perdere completamente la concentrazione.",
    "Non ho mai risposto 'niente' alla domanda 'Cosa indossi?'.",
    "Non ho mai fatto salire la tensione erotica in chat prolungando volontariamente l'attesa.",
    "Non ho mai scritto 'se solo fossi qui…' per far volare l'immaginazione.",
    "Non ho mai continuato a chattare con qualcuno chiudendomi in bagno per avere privacy.",
    "Non ho mai archiviato una chat compromettente per paura di essere scoperto.",
    "Non ho mai cambiato il nome di un contatto in rubrica per nascondere un flirt.",
    "Non ho mai pubblicato una Storia sui social con il solo scopo di farla vedere a una persona specifica.",
    "Non ho mai zoomato su una foto di qualcuno con pensieri poco casti.",
    "Non ho mai salvato una foto di qualcuno perché la reputavo troppo sexy per perderla.",
    "Non ho mai mandato un 'buongiorno' che era in realtà una chiara provocazione.",
    "Non ho mai confessato una fantasia erotica prima in chat e poi dal vivo.",
    "Non ho mai riaperto una vecchia chat spinto esclusivamente dalla nostalgia fisica.",
    "Non ho mai mandato un messaggio che da sobrio non avrei mai avuto il coraggio di scrivere.",
    "Non ho mai chiesto a qualcuno di cancellare una nostra conversazione per sicurezza.",
    "Non ho mai mandato foto di dettagli del mio outfit per far immaginare il resto.",
    "Non ho mai fatto una videochiamata che ha preso una piega molto più intima del previsto.",
    "Non ho mai fatto sesso in auto.",
    "Non ho mai fatto sesso sotto la doccia o in una vasca.",
    "Non ho mai fatto sesso all'aperto, in spiaggia o in piscina.",
    "Non ho mai fatto sesso in un hotel lontano da casa.",
    "Non ho mai fatto sesso sul tavolo della cucina o sul divano.",
    "Non ho mai fatto sesso contro una porta o su un balcone.",
    "Non ho mai fatto sesso sapendo che nelle stanze accanto c'erano altre persone.",
    "Non ho mai fatto sesso cercando di non fare assolutamente alcun rumore.",
    "Non ho mai fatto sesso tenendo la musica alta per coprire i suoni.",
    "Non ho mai fatto sesso davanti a uno specchio.",
    "Non ho mai fatto sesso in un luogo così scomodo solo perché non riuscivamo ad aspettare.",
    "Non ho mai fatto sesso la sera dell'ultimo giorno di una vacanza.",
    "Non ho mai fatto sesso al primo appuntamento.",
    "Non ho mai fatto sesso con qualcuno incontrato alla stessa festa da poche ore.",
    "Non ho mai fatto sesso con un amico o un collega di lavoro.",
    "Non ho mai fatto sesso con qualcuno sapendo che non ci sarebbe stato un domani.",
    "Non ho mai fatto sesso subito dopo un furioso litigio.",
    "Non ho mai fatto sesso poco prima che arrivasse qualcuno a casa.",
    "Non ho mai fatto sesso in pieno giorno con le finestre aperte.",
    "Non ho mai fatto sesso nel cuore della notte svegliandomi apposta.",
    "Non ho mai fatto sesso e poi ordinato cibo spazzatura alle tre del mattino.",
    "Non ho mai fatto sesso con qualcuno molto più grande o esperto di me.",
    "Non ho mai fatto sesso con qualcuno che mi intimidiva, ma che fisicamente mi faceva impazzire.",
    "Non ho mai fatto sesso con qualcuno con cui era impossibile parlare, ma a letto c'era sintonia perfetta.",
    "Non ho mai fatto sesso lo stesso giorno in cui ho chiuso una relazione.",
    "Non ho mai fatto sesso usato puramente come antistress o per dimenticare un ex.",
    "Non ho mai fatto durare i preliminari molto più del sesso stesso.",
    "Non ho mai fatto sesso così in fretta da riderne subito dopo.",
    "Non ho mai fatto trasformare un innocente massaggio alla schiena in qualcosa di molto più spinto.",
    "Non ho mai usato oli o cibi durante i preliminari.",
    "Non ho mai usato il dirty talk (parole spinte) a letto.",
    "Non ho mai fatto sesso sperimentando una posizione mai provata prima.",
    "Non ho mai fatto sesso bendato o legando le mani al partner.",
    "Non ho mai fatto giochi di ruolo a letto interpretando un personaggio.",
    "Non ho mai usato accessori o sex toys in coppia.",
    "Non ho mai riso durante il sesso per una piccola goffaggine.",
    "Non ho mai fatto sesso così intensamente da perdere la cognizione del tempo.",
    "Non ho mai fatto sesso con sottofondo una playlist creata appositamente.",
    "Non ho mai fatto sesso con una canzone in sottofondo che ora non riesco più ad ascoltare serenamente.",
    "Non ho mai fatto sesso venendo interrotto nel momento clou da una telefonata di un parente.",
    "Non ho mai avuto una relazione basata esclusivamente sulla chimica fisica.",
    "Non ho mai avuto un 'amico con benefici'.",
    "Non ho mai stabilito regole chiare per una relazione puramente fisica per poi infrangerle subito.",
    "Non ho mai detto 'non affezioniamoci' sapendo benissimo che era già troppo tardi.",
    "Non ho mai mantenuto viva una storia a distanza quasi solo grazie al sexting.",
    "Non ho mai perso la lucidità al solo sfioramento da parte di una persona.",
    "Non ho mai desiderato qualcuno visceralmente solo per il suo modo di guardarmi o per il suo profumo.",
    "Non ho mai trasformato una discussione accesissima in un momento di passione travolgente.",
    "Non ho mai usato la gelosia solo per alimentare la tensione sessuale.",
    "Non ho mai fatto finta di essere disinteressato mentre dentro di me l'ormone impazziva.",
    "Non ho mai fatto aspettare un bacio di proposito per renderlo ancora più intenso.",
    "Non ho mai avuto un'intesa formata esclusivamente da sguardi carichi di malizia.",
    "Non ho mai trovato terribilmente eccitante qualcuno proprio perché riusciva a trattenere il desiderio.",
    "Non ho mai vissuto una serata in cui la parte migliore è stata l'attesa di rimanere da soli.",
    "Non ho mai ricevuto un 'dirty talk' che mi ha spiazzato in positivo.",
    "Non ho mai chiesto apertamente a un partner le sue fantasie più recondite.",
    "Non ho mai confessato una fantasia temendo di sembrare troppo perverso.",
    "Non ho mai accettato di provare qualcosa di nuovo a letto per pura curiosità.",
    "Non ho mai usato un soprannome molto intimo e malizioso a letto.",
    "Non ho mai chiesto a qualcuno di farsi guidare completamente, abbandonando il controllo.",
    "Non ho mai fantasticato su un incontro bollente sul posto di lavoro o all'università.",
    "Non ho mai fantasticato di fare l'amore su un mezzo di trasporto.",
    "Non ho mai fantasticato di spogliare lentamente qualcuno con i denti.",
    "Non ho mai comprato lingerie o intimo specifico per stupire una persona.",
    "Non ho mai tenuto l'intimo addosso durante il sesso solo perché mi faceva sentire più sexy.",
    "Non ho mai fatto scivolare giù una spallina di proposito per provocare.",
    "Non ho mai lasciato deliberatamente slacciati gli ultimi bottoni della camicia per attirare sguardi.",
    "Non ho mai avuto la chiara sensazione di essere spogliato con gli occhi.",
    "Non ho mai giocato con i capelli in modo volutamente seducente per farmi notare.",
    "Non ho mai sfiorato la coscia di qualcuno sotto il tavolo durante una cena con altre persone.",
    "Non ho mai trovato incredibilmente eccitante il calore della pelle di qualcuno sfiorato per sbaglio.",
    "Non ho mai lasciato un succhiotto o un graffio evidente sul corpo di qualcuno.",
    "Non ho mai dovuto indossare sciarpe o dolcevita per nascondere i segni di una notte brava.",
    "Non ho mai indossato di nuovo un capo senza lavarlo perché manteneva il profumo di una notte di passione.",
    "Non ho mai trovato irresistibilmente sexy un gesto banalissimo e quotidiano (come guidare o cucinare).",
    "Non ho mai fissato qualcuno salire le scale con pensieri tutt'altro che casti.",
    "Non ho mai percepito un'enorme tensione sessuale in un tocco apparentemente innocente.",
    "Non ho mai organizzato una serata finta-tranquilla calcolando in realtà ogni mossa per finire a letto.",
    "Non ho mai invitato qualcuno a cena con intenzioni non esattamente culinarie.",
    "Non ho mai trasformato una bevuta 'di un solo bicchiere' in una nottata a luci rosse.",
    "Non ho mai preparato le luci soffuse in casa prima che qualcuno arrivasse.",
    "Non ho mai legato il ricordo di uno specifico locale o quartiere a una notte indimenticabile.",
    "Non ho mai omesso dettagli di una storia agli amici perché erano troppo espliciti o imbarazzanti.",
    "Non ho mai esagerato un po’ il racconto di un incontro hot per fare il gradasso.",
    "Non ho mai avuto un incontro iniziato guardando un film di cui non abbiamo visto nemmeno cinque minuti.",
    "Non ho mai vissuto una notte talmente folle e passionale da sembrare finta.",
    "Non ho mai vissuto una notte di cui ricordo più i brividi fisici che le parole dette.",
    "Non ho mai dovuto allontanarmi fisicamente da qualcuno per non rischiare di saltargli addosso in pubblico.",
    "Non ho mai avuto il desiderio improvviso di baciare qualcuno durante un saluto formale con la guancia.",
    "Non ho mai fatto un respiro profondo per cercare (invano) di placare il desiderio.",
    "Non ho mai finto interesse per una conversazione noiosa mentre in realtà pensavo solo a spogliare l'altro.",
    "Non ho mai accorciato intenzionalmente le distanze fisiche, spostando la sedia, per far salire la tensione.",
    "Non ho mai sentito il mio respiro farsi pesante per un avvicinamento inatteso.",
    "Non ho mai usato un tono di voce più basso e profondo per sembrare più seducente.",
    "Non ho mai finto di non accorgermi di un clima chiaramente erotico.",
    "Non ho mai corso il rischio di rovinare una bella amicizia cedendo alla chimica fisica.",
    "Non ho mai ripensato a una notte di sesso chiedendomi come sarebbe andata se mi fossi fermato prima.",
    "Non ho mai ripensato a un'occasione sprecata in cui avrei solo dovuto dire 'sì'.",
    "Non ho mai vissuto un momento in cui un semplice 'resta a dormire' ha svoltato la serata.",
    "Non ho mai creduto che il mio lato erotico fosse molto più selvaggio di quanto mostro normalmente.",
    "Non ho mai lasciato che il desiderio fisico mi facesse prendere decisioni altamente discutibili.",
    "Non ho mai sentito che il mio corpo reagiva da solo prima ancora che il mio cervello approvasse.",
    "Non ho mai imparato qualcosa di nuovo su me stesso dopo un incontro particolarmente intenso.",
    "Non ho mai trovato incredibilmente eccitante la fase in cui ci si sveste con calma guardandosi negli occhi."
];