const dataSocial = [
    "Non ho mai passato ore a fare 'scroll infinito' sui social perdendo completamente la cognizione del tempo.",
    "Non ho mai sbloccato il telefono solo per guardare l'ora e finito per chiudere Instagram mezz'ora dopo senza sapere che ore fossero.",
    "Non ho mai visualizzato un messaggio scomodo e finto di non averlo letto, rispondendo giorni dopo con 'Scusa, non mi era arrivata la notifica!'.",
    "Non ho mai lasciato qualcuno in 'visualizzato' solo per fargli credere di avere una vita piena di impegni.",
    "Non ho mai cancellato freneticamente un messaggio in chat prima che l'altra persona potesse leggerlo.",
    "Non ho mai scritto un messaggio lunghissimo per poi cancellarlo tutto all'ultimo e rispondere con un freddo 'Ok'.",
    "Non ho mai controllato spasmodicamente l'ultimo accesso o lo stato 'online' di qualcuno su WhatsApp.",
    "Non ho mai chiuso la chat di corsa appena vedevo la scritta 'sta scrivendo...' per non sembrare troppo ansioso/a di rispondere.",
    "Non ho mai postato una Storia su Instagram con il solo scopo di farla vedere a una persona in particolare.",
    "Non ho mai controllato la lista delle visualizzazioni di una mia Storia dieci volte di fila sperando ci fosse QUEL nome.",
    "Non ho mai cancellato un post o una Storia poco dopo averla pubblicata perché non aveva ricevuto abbastanza like.",
    "Non ho mai postato una citazione, una frase o una canzone palesemente come frecciatina per un ex o un crush.",
    "Non ho mai cambiato la mia foto profilo subito dopo una rottura o un litigio per mostrare quanto stessi bene.",
    "Non ho mai usato un profilo falso (o quello di un amico) per spiare le Storie di qualcuno in totale anonimato.",
    "Non ho mai stalkerato un ex o la sua nuova fiamma fino ad arrivare ad analizzare i post del 2014.",
    "Non ho mai messo per sbaglio un like a una foto vecchissima durante una sessione di stalking estremo, sudando freddo.",
    "Non ho mai spiato i profili di persone che conosco a malapena solo per farmi gli affari loro.",
    "Non ho mai scaricato un'app di terze parti solo per scoprire chi avesse smesso di seguirmi.",
    "Non ho mai smesso di seguire qualcuno in un momento di pura rabbia, per poi pentirmene e dovergli richiedere il follow.",
    "Non ho mai bloccato e sbloccato una persona a ripetizione per mandarla in confusione o per attirare l'attenzione.",
    "Non ho mai silenziato le Storie di un amico perché non sopportavo più i suoi continui aggiornamenti.",
    "Non ho mai postato una foto di gruppo in cui io venivo benissimo, ignorando totalmente il fatto che il mio amico di fianco fosse venuto malissimo.",
    "Non ho mai scattato 50 selfie identici per sceglierne solo uno, che poi ho comunque modificato.",
    "Non ho mai usato Facetune, Photoshop o filtri miracolosi per snellirmi, togliermi brufoli o cambiarmi i connotati prima di postare una foto.",
    "Non ho mai finto di trovarmi in una location esclusiva o in vacanza ripostando in modo tattico foto vecchie.",
    "Non ho mai fatto finta di conoscere un trend o un meme virale solo per non sembrare fuori dal mondo.",
    "Non ho mai inoltrato uno screenshot compromettente nel gruppo sbagliato, scatenando il panico.",
    "Non ho mai litigato ferocemente con uno sconosciuto nei commenti di un post pubblico.",
    "Non ho mai scritto un commento passivo-aggressivo sotto il post di un conoscente o parente.",
    "Non ho mai cercato il mio stesso nome su Google per vedere cosa usciva fuori.",
    "Non ho mai finto di avere il telefono scarico o la linea assente per chiudere una chiamata noiosa.",
    "Non ho mai spiato la posizione in tempo reale di amici o partner tramite app (Snap Map, Trova i miei amici, ecc.).",
    "Non ho mai partecipato a un sondaggio anonimo su Instagram per dire cattiverie, per poi scoprire che il creatore poteva vedere i nomi.",
    "Non ho mai attivato la 'modalità aereo' per leggere un messaggio senza far apparire le spunte blu.",
    "Non ho mai cancellato la cronologia delle mie ricerche per pura vergogna di quello che avevo cercato.",
    "Non ho mai cancellato la cronologia del browser un attimo prima di prestare il telefono a qualcuno.",
    "Non ho mai usato un'app di dating (Tinder, Bumble, ecc.) fingendo di cercare solo 'nuove amicizie'.",
    "Non ho mai scorso i profili su un'app di dating solo per giudicare e deridere le biografie degli altri.",
    "Non ho mai 'ghostato' qualcuno bloccandolo ovunque, senza fornire uno straccio di spiegazione.",
    "Non ho mai mentito sulla mia età, sul mio lavoro o sul mio aspetto fisico su un profilo social o di incontri.",
    "Non ho mai messo in pausa un film per rispondere a un messaggio, e finito per chattare un'ora dimenticandomi cosa stessi guardando.",
    "Non ho mai fatto un 'detox' dai social annunciandolo platealmente, per poi rientrare in silenzio dopo appena due giorni.",
    "Non ho mai disinstallato e reinstallato un'app tossica per me (Instagram, TikTok) tre volte nella stessa settimana.",
    "Non ho mai inviato un messaggio 'per sbaglio' a un ex o a un crush solo per avere una scusa per rompere il ghiaccio.",
    "Non ho mai finto di essere un esperto di geopolitica, medicina o finanza discutendo con gente a caso nei commenti.",
    "Non ho mai usato il Wi-Fi del vicino di casa o di un locale scroccando la password.",
    "Non ho mai fatto uno screenshot a una foto effimera (inviata per essere vista una sola volta) rischiando di far arrivare la notifica all'altra persona.",
    "Non ho mai fatto 'swipe up' o reagito alla Storia di un crush con un'emoji e poi sudato freddo sperando in una risposta.",
    "Non ho mai finto di non aver visto il tag in una foto bruttissima in cui mi avevano menzionato, evitando di metterci like.",
    "Non ho mai rimosso furtivamente il tag dal mio nome in una foto di gruppo perché non mi piaceva come ero venuto.",
    "Non ho mai usato la modalità 'non disturbare' solo per poter ignorare una persona specifica che continuava a scrivermi.",
    "Non ho mai spiato le storie di Instagram usando siti esterni anonimi per non lasciare traccia.",
    "Non ho mai fatto scorrere il dito su TikTok mentre ero seduto in bagno fino a farmi addormentare le gambe.",
    "Non ho mai riso per un meme inviato da un amico che non faceva per nulla ridere, rispondendo con dieci emoji che piangono dal ridere.",
    "Non ho mai attivato e disattivato il WiFi o i Dati Mobili per far finta che un messaggio non partisse a causa della 'connessione'.",
    "Non ho mai creato un gruppo WhatsApp da solo (o con qualcuno che poi ho cacciato) solo per usarlo come blocco note personale.",
    "Non ho mai messo il telefono in modalità silenziosa per poi scordarmelo lì, perdendo chiamate importantissime.",
    "Non ho mai finto che un messaggio o un commento imbarazzante fosse stato scritto da un 'amico che mi aveva rubato il telefono'."
];